# Data Information

This notebook goes over information of the three files we will be working with

- Separations: data on the events of employees leaving federal workforce
- Accessions: data on the events employees joining federal workforce
- Employment: various descriptive data on the federal workforce

# Load Data

In [33]:
from pathlib import Path
import sys

sys.path.append(str(Path.cwd().parent))
from scripts.data_loader import load_r2_data

In [34]:
#  Load dataframes (choose most recent)
s_df = load_r2_data("separations", year=2026, month=2)
a_df = load_r2_data("accessions", year=2026, month=2)
e_df = load_r2_data("employment", year=2026, month=2)

/Users/destin/Projects/federal-doge-study/.venv/lib/python3.9/site-packages/boto3/compat.py:89: PythonDeprecationWarning: Boto3 will no longer support Python 3.9 starting April 29, 2026. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.10 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

  loading separations/2026/separations_202602.txt …

/Users/destin/Projects/federal-doge-study/.venv/lib/python3.9/site-packages/boto3/compat.py:89: PythonDeprecationWarning: Boto3 will no longer support Python 3.9 starting April 29, 2026. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.10 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

  loading accessions/2026/accessions_202602.txt …

/Users/destin/Projects/federal-doge-study/.venv/lib/python3.9/site-packages/boto3/compat.py:89: PythonDeprecationWarning: Boto3 will no longer support Python 3.9 starting April 29, 2026. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.10 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

  loading employment/2026/employment_202602.txt …

In [35]:
# Build code -> descriptor lookup dicts from paired columns in each df
def build_lookups(df):
    lookups = {}
    for col in df.columns:
        if col.endswith("_code"):
            descriptor = col[:-5]  # strip "_code"
            if descriptor in df.columns:
                lookups[col] = (
                    df[[col, descriptor]]
                    .drop_duplicates()
                    .dropna(subset=[col])
                    .set_index(col)[descriptor]
                    .to_dict()
                )
    return lookups

s_lookups = build_lookups(s_df)
a_lookups = build_lookups(a_df)
e_lookups = build_lookups(e_df)

print(f"Separations: {len(s_lookups)} code -> descriptor mappings built")
print(f"Accessions:  {len(a_lookups)} code -> descriptor mappings built")
print(f"Employment:  {len(e_lookups)} code -> descriptor mappings built")

Separations: 22 code -> descriptor mappings built
Accessions:  22 code -> descriptor mappings built
Employment:  21 code -> descriptor mappings built

# Data description

## Separations
Records of federal employees who left government. One row = one separation event.

In [36]:
import pandas as pd

code_cols = [c for c in s_df.columns if c.endswith("_code")]
print(f"Shape: {s_df.shape[0]:,} rows x {s_df.shape[1]} columns")
print(f"\nCode columns ({len(code_cols)}):")
print(code_cols)
print(f"\nAll columns:")
print(s_df.dtypes.to_string())

Shape: 19,170 rows x 68 columns

Code columns (25):
['agency_code', 'agency_subelement_code', 'appointment_type_code', 'bargaining_unit_code', 'consolidated_statistical_area_code', 'core_based_statistical_area_code', 'duty_station_code', 'duty_station_country_code', 'duty_station_county_code', 'duty_station_state_country_territory_code', 'education_level_code', 'flsa_category_code', 'locality_pay_area_code', 'occupational_category_code', 'occupational_group_code', 'occupational_series_code', 'pay_basis_code', 'pay_plan_code', 'personnel_office_identifier_code', 'position_occupied_code', 'separation_category_code', 'step_or_rate_type_code', 'supervisory_status_code', 'tenure_code', 'work_schedule_code']

All columns:
age_bracket                                   object
agency                                        object
agency_code                                   object
agency_subelement                             object
agency_subelement_code                        object
annualized_adjusted_basic_pay                 object
appointment_not_to_exceed_date                object
appointment_type                              object
appointment_type_code                         object
bargaining_unit                               object
bargaining_unit_code                          object
bargaining_unit_status                        object
cfo_act_agency_indicator                      object
consolidated_statistical_area                 object
consolidated_statistical_area_code            object
core_based_statistical_area                   object
core_based_statistical_area_code              object
count                                          int64
drp_indicator                                 object
duty_station_code                             object
duty_station_country                          object
duty_station_country_code                     object
duty_station_county                           object
duty_station_county_code                      object
duty_station_state                            object
duty_station_state_abbreviation               object
duty_station_state_country_territory_code     object
education_level                               object
education_level_bracket                       object
education_level_code                          object
flsa_category                                 object
flsa_category_code                            object
grade                                         object
length_of_service_years                      float64
locality_pay_area                             object
locality_pay_area_code                        object
nsftp_indicator                               object
occupational_category                         object
occupational_category_code                    object
occupational_group                            object
occupational_group_code                       object
occupational_series                           object
occupational_series_code                      object
pay_basis                                     object
pay_basis_code                                object
pay_plan                                      object
pay_plan_code                                 object
personnel_action_effective_date_yyyymm         int64
personnel_office_identifier_code              object
position_occupied                             object
position_occupied_code                        object
separation_category                           object
separation_category_code                      object
service_computation_date_leave                object
stem_occupation                               object
stem_occupation_type                          object
step_or_rate_type                             object
step_or_rate_type_code                        object
supervisory_status                            object
supervisory_status_code                      float64
tenure                                        object
tenure_code                                  float64
veteran_indicator                             object
work_schedule                                 object
work_schedule_code                            object
year                                           int64
month                                          int64
data_type                                     object

In [37]:
# Sample — working with code columns
s_df[["separation_category_code", "agency_subelement_code", "age_bracket", "tenure_code", "work_schedule_code"]].head(5)

,separation_category_code,agency_subelement_code,age_bracket,tenure_code,work_schedule_code
0,SD,ST00,55-59,1.0,F
1,SD,AF1M,60-64,1.0,F
2,SD,AF1M,60-64,1.0,F
3,SD,AF1M,60-64,1.0,F
4,SD,AF1M,65 OR MORE,1.0,F

In [38]:
# Key lookup tables for separations
for key in ["separation_category_code", "agency_code", "tenure_code", "work_schedule_code", "education_level_code", "pay_plan_code"]:
    if key in s_lookups:
        print(f"=== {key} ===")
        print(pd.Series(s_lookups[key]).sort_index().to_string())
        print()

=== separation_category_code ===
SA    TRANSFER OUT - INDIVIDUAL TRANSFER
SB          TRANSFER OUT - MASS TRANSFER
SC                                  QUIT
SD                RETIREMENT - VOLUNTARY
SE                RETIREMENT - EARLY OUT
SG                    RETIREMENT - OTHER
SH              REDUCTION IN FORCE (RIF)
SJ      TERMINATION (EXPIRED APPT/OTHER)
SL                      OTHER SEPARATION

=== agency_code ===
AF                 DEPARTMENT OF THE AIR FORCE
AG                   DEPARTMENT OF AGRICULTURE
AH       NAT FOUNDATION ON ARTS AND HUMANITIES
AM           U.S. AGENCY FOR INTERNATIONAL DEV
AN              AFRICAN DEVELOPMENT FOUNDATION
AR                      DEPARTMENT OF THE ARMY
AU           FEDERAL LABOR RELATIONS AUTHORITY
BF     DEFENSE NUCLEAR FACILITIES SAFETY BOARD
BG        PENSION BENEFIT GUARANTY CORPORATION
BO             OFFICE OF MANAGEMENT AND BUDGET
BT    ARCHITECTL & TRANS BARRIER COMPLIANCE BD
CC                  COMMISSION ON CIVIL RIGHTS
CE                COUNCIL OF ECONOMIC ADVISERS
CM                      DEPARTMENT OF COMMERCE
CT        COMMODITY FUTURES TRADING COMMISSION
CU        NATIONAL CREDIT UNION ADMINISTRATION
DD                       DEPARTMENT OF DEFENSE
DJ                       DEPARTMENT OF JUSTICE
DL                         DEPARTMENT OF LABOR
DN                        DEPARTMENT OF ENERGY
DO                    OFC OF THE NAT CYBER DIR
EB     EXPORT-IMPORT BANK OF THE UNITED STATES
EC                    OFFICE OF ADMINISTRATION
ED                     DEPARTMENT OF EDUCATION
EE     EQUAL EMPLOYMENT OPPORTUNITY COMMISSION
EO    MORRIS K. UDALL & STEWART L. UDALL FOUND
EP             ENVIRONMENTAL PROTECTION AGENCY
FC           FEDERAL COMMUNICATIONS COMMISSION
FD       FEDERAL DEPOSIT INSURANCE CORPORATION
FL                  FARM CREDIT ADMINISTRATION
FM      FED MEDIATION AND CONCILIATION SERVICE
FQ     COURT SERVICES AND OFFENDR SUPERVSN AGY
FR                      FEDERAL RESERVE SYSTEM
FT                    FEDERAL TRADE COMMISSION
GB                                         DFC
GG                 OFFICE OF GOVERNMENT ETHICS
GJ                              PRESIDIO TRUST
GS             GENERAL SERVICES ADMINISTRATION
GW     INTER BOUND AND WATER COMM U.S. SECTION
GY     INTERNATIONAL JOINT CMSN: U.S. & CANADA
HD              U.S. HOLOCAUST MEMORIAL MUSEUM
HE     DEPARTMENT OF HEALTH AND HUMAN SERVICES
HF              FEDERAL HOUSING FINANCE AGENCY
HP        ADV COUNCIL ON HISTORIC PRESERVATION
HS             DEPARTMENT OF HOMELAND SECURITY
HU    DEPARTMENT OF HOUSING AND URBAN DEVELOPM
IB                 U.S.AGENCY FOR GLOBAL MEDIA
IN                      DEPARTMENT OF INTERIOR
JL                             JUDICIAL BRANCH
KS     CORP FOR NATIONAL AND COMMUNITY SERVICE
LF                 FEDERAL ELECTION COMMISSION
LP                GOVERNMENT PUBLISHING OFFICE
MA                    MARINE MAMMAL COMMISSION
MI            MILLENNIUM CHALLENGE CORPORATION
NF                 NATIONAL SCIENCE FOUNDATION
NL              NATIONAL LABOR RELATIONS BOARD
NN    NAT AERONAUTICS AND SPACE ADMINISTRATION
NQ     NAT ARCHIVES AND RECORDS ADMINISTRATION
NU               NUCLEAR REGULATORY COMMISSION
NV                      DEPARTMENT OF THE NAVY
OM              OFFICE OF PERSONNEL MANAGEMENT
PU                                 PEACE CORPS
RF      FED RETIREMENT THRIFT INVESTMENT BOARD
RH                ARMED FORCES RETIREMENT HOME
RR                   RAILROAD RETIREMENT BOARD
RS      FED MINE SAFETY AND HEALTH REVIEW CMSN
SB               SMALL BUSINESS ADMINISTRATION
SE          SECURITIES AND EXCHANGE COMMISSION
SK          CONSUMER PRODUCT SAFETY COMMISSION
SM                     SMITHSONIAN INSTITUTION
SS                    SELECTIVE SERVICE SYSTEM
ST                         DEPARTMENT OF STATE
SZ              SOCIAL SECURITY ADMINISTRATION
TB        NATIONAL TRANSPORTATION SAFETY BOARD
TC         U.S. INTERNATIONAL TRADE COMMISSION
TD                DEPARTMENT OF TRANSPORTATION
TN     OFFICE OF THE U.S. TRADE REPRESENTATIVE
TR                      DEPARTMENT OF TREASURY
TS     OFFICE OF SCIENCE AND TECHNOLOGY POLICY
UJ         JAPAN-UNITED STATES FRIENDSHIP CMSN
VA              DEPARTMENT OF VETERANS AFFAIRS
VD       PRIVACY AND CIVIL LIBERTIES OVERSIGHT

=== tenure_code ===
0.0    NO TENURE GROUP - EMPLOYEES (E.G., TEMPORARIES...
1.0    TENURE GROUP 1 - CAREER OR SERVING AN APPOINTM...
2.0    TENURE GROUP 2 - CAREER-CONDITIONAL OR OTHER A...
3.0    TENURE GROUP 3 - TAPER/TERM OR PROVISIONAL OR ...

=== work_schedule_code ===
F                                            FULL-TIME
G                                   FULL-TIME SEASONAL
I                                         INTERMITTENT
J                                INTERMITTENT SEASONAL
P                                            PART-TIME
Q                                   PART-TIME SEASONAL
R    A SCHEDULE REQUIRED WHEN AN EMPLOYEE HAS ELECT...
S                                 PART-TIME JOB SHARER

=== education_level_code ===
*                                               INVALID
01    NO FORMAL EDUCATION OR SOME ELEMENTARY SCHOOL ...
02         ELEMENTARY SCHOOL COMPLETED - NO HIGH SCHOOL
03                  SOME HIGH SCHOOL - DID NOT COMPLETE
04    HIGH SCHOOL GRADUATE OR CERTIFICATE OF EQUIVAL...
05     TERMINAL OCCUPATIONAL PROGRAM - DID NOT COMPLETE
06    TERMINAL OCCUPATIONAL PROGRAM - CERTIFICATE OF...
07                    SOME COLLEGE - LESS THAN ONE YEAR
08                                     ONE YEAR COLLEGE
09                                    TWO YEARS COLLEGE
10                                     ASSOCIATE DEGREE
11                                  THREE YEARS COLLEGE
12                                   FOUR YEARS COLLEGE
13                                    BACHELOR'S DEGREE
14                                      POST-BACHELOR'S
15                                   FIRST PROFESSIONAL
16                              POST-FIRST PROFESSIONAL
17                                      MASTER'S DEGREE
18                                        POST-MASTER'S
19                                    SIXTH-YEAR DEGREE
20                                      POST-SIXTH YEAR
21                                     DOCTORATE DEGREE
22                                       POST-DOCTORATE

=== pay_plan_code ===
AD    ADMINISTRATIVELY DETERMINED RATES, NOT ELSEWHE...
AL                            ADMINISTRATIVE LAW JUDGES
AT    FEDERAL AVIATION ADMINISTRATION AIR TRAFFIC CO...
BB            NONSUPERVISORY - NEGOTIATED PAY EMPLOYEES
BN    EMPLOYEES IN THE NAVAL NUCLEAR PROPULSION PROG...
CA                            BOARD OF CONTRACT APPEALS
CE                        CONTRACT EDUCATION--YEAR LONG
CG                                     CORPORATE GRADED
CN    BUREAU OF CONSUMER FINANCIAL PROTECT(CFPB) IND...
CT    NONSUPERVISORY EMPLOYEES AT COMMODITY FUTURES ...
CU                               CREDIT UNION EMPLOYEES
CY                      CONTRACT EDUCATION--SCHOOL YEAR
DA                         DEMONSTRATION ADMINISTRATIVE
DB               DEMONSTRATION ENGINEERS AND SCIENTISTS
DC    POSITIONS DESIGNATED AND PAID RATES OF BASIC P...
DE    DEMONSTRATION ENGINEERS AND SCIENTISTS TECHNIC...
DG                                DEMONSTRATION GENERAL
DJ                         DEMONSTRATION ADMINISTRATIVE
DK                        DEMONSTRATION GENERAL SUPPORT
DL    POSITIONS DESIGNATED AND PAID RATES OF BASIC P...
DN    DEFENSE NUCLEAR FACILITIES SAFETY BOARD EXCEPT...
DO    BUSINESS MANAGEMENT AND PROFESSIONAL CAREER PA...
DP                           DEMONSTRATION PROFESSIONAL
DR      DEMONSTRATIION AIR FORCE SCIENTIST AND ENGINEER
DS                             DEMONSTRATION SPECIALIST
DT                             DEMONSTRATION TECHNICIAN
DU    MISSION SUPPORT CAREER PATH, AIR FORCE RESEARC...
DX    TECHNICIAN CAREER PATH, AIR FORCE RESEARCH LAB...
ED                               EXPERT (5 U.S.C. 3109)
EE                                       EXPERT (OTHER)
EF                           CONSULTANT (5 U.S.C. 3109)
EH            ADVISORY COMMITTEE MEMBER (5 U.S.C. 3109)
EI                    ADVISORY COMMITTEE MEMBER (OTHER)
EJ    THE DEPARTMENT OF ENERGY ORGANIZATION ACT EXCE...
EL    NON-EXECUTIVE POSITIONS AT THE FEDERAL HOUSING...
EN    NATIONAL NUCLEAR SECURITY ADMINISTRATION EXCEP...
ES                             SENIOR EXECUTIVE SERVICE
EV    FEDERAL AVIATION ADMINISTRATION EXECUTIVE COMP...
EX                                        EXECUTIVE PAY
FE                               SENIOR FOREIGN SERVICE
FG                      SIMILAR TO THE GENERAL SCHEDULE
FO                             FOREIGN SERVICE OFFICERS
FP                            FOREIGN SERVICE PERSONNEL
FV    FEDERAL AVIATION ADMINISTRATION CORE COMPENSAT...
FW    WAGE GRADE (SIMILAR TO THE NONSUPERVISORY PAY ...
GG                   GRADES SIMILAR TO GENERAL SCHEDULE
GL    GS EMPLOYEES IN GRADES 3 THROUGH 10 PAID A LAW...
GP    GS PHYSICIANS, PODIATRISTS, AND DENTISTS PAID ...
GS                                     GENERAL SCHEDULE
GW    GS EMPLOYEES IN GRADES 1-15 PAID A WILDLAND FI...
IC    EMPLOYEES HOLDING INCIDENT MANAGEMENT CADRE OF...
IE    SENIOR INTELLIGENCE EXECUTIVE SERVICE (SIES) P...
IH    TEMPORARY EMPLOYEES HIRED IN RESPONSE TO A DIS...
IJ                           IMMIGRATION JUDGE SCHEDULE
IM    EMPLOYEES HOLDING INCIDENT MANAGEMENT POSITION...
IP       SENIOR INTELLIGENCE PROFESSIONAL (SIP) PROGRAM
IR    INTERNAL REVENUE SERVICE BROADBAND CLASSIFICAT...
KE    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
KG                            NON-CRAFT NON-SUPERVISORY
KI    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
KX    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
LE        UNITED STATES SECRET SERVICE UNIFORM DIVISION
MC    EMPLOYEES OF THE MILLENNIUM CHALLENGE CORPORAT...
NB       OFFICE OF THE COMPTROLLER OF THE CURRENCY ONLY
NC                               ADMINISTRATIVE SUPPORT
ND             DEMONSTRATION SCIENTIFIC AND ENGINEERING
NG                        DEMONSTRATION GENERAL SUPPORT
NH    BUSINESS MANAGEMENT AND TECHNICAL MANAGEMENT P...
NJ                         TECHNICAL MANAGEMENT SUPPORT
NK                               ADMINISTRATION SUPPORT
NL    NONAPPROPRIATED FUNDS - LEADER - FEDERAL WAGE ...
NM                             SUPERVISORS AND MANAGERS
NO               ADMINISTRATIVE SPECIALIST/PROFESSIONAL
NP                 SCIENCE AND ENGINEERING PROFESSIONAL
NQ    EMPLOYEES IN THE NATIONAL NUCLEAR SECUIRTY ADM...
NR                    SCIENCE AND ENGINEERING TECHNICAL
NT           DEMONSTRATION ADMINISTRATIVE AND TECHNICAL
NV    EMPLOYEES IN THE NATIONAL NUCLEAR SECURITY ADM...
NY    ALL OTHER POSITIONS IN THE CORPORATION FOR NAT...
PG                               PRINTING OFFICE GRADES
RF    EMPLOYEES APPOINTED AND COMPENSATED AS SPECIAL...
RG    SCIENTISTS APPOINTED AS FELLOWS AND COMPENSATE...
RS                   SENIOR BIOMEDICAL RESEARCH SERVICE
SK    NON-SUPERVISORY POSITIONS EMPLOYED BY THE SECU...
SL                               SENIOR LEVEL POSITIONS
SO    EXECUTIVE POSITIONS EMPLOYED BY THE SECURITIES...
SP                                          PARK POLICE
SR              STATUTORY RATES NOT ELSEWHERE SPECIFIED
ST                          SCIENTIFIC AND PROFESSIONAL
SV    TRANSPORTATION SECURITY ADMINISTRATION EMPLOYE...
TP                                   TEACHING POSITIONS
TR    POLICE FORCES OF THE U.S. MINT AND BUREAU OF E...
VC                                      CANTEEN SERVICE
VH         PROFESSIONAL, ADMINISTRATIVE, AND MANAGERIAL
VM                                   MEDICAL AND DENTAL
VN                                              NURSING
VP       CLINICAL PODIATRISTS AND OPTOMETRISTS SCHEDULE
WA    NAVIGATIONAL LOCK AND DAM OPERATIONS AND MAINT...
WB    WAGE POSITIONS UNDER THE FEDERAL WAGE SYSTEM N...
WD    PRODUCTION FACILITATING NON-SUPERVISORY - FEDE...
WE                               CURRENCY MANUFACTURING
WG    NONSUPERVISORY PAY SCHEDULES - FEDERAL WAGE SY...
WL            LEADER PAY SCHEDULE - FEDERAL WAGE SYSTEM
WM                MARITIME PAY SCHEDULES--5 U.S.C. 5348
WQ    AIRCRAFT, ELECTRONIC EQUIPMENT, AND OPTICAL IN...
WS      SUPERVISORY PAY SCHEDULES - FEDERAL WAGE SYSTEM
WT    APPRENTICES AND SHOP TRAINEES - FEDERAL WAGE S...
WY    NAVIGATIONAL LOCK & DAM OPERATION & MAINTENANC...
XA    SPECIAL OVERLAP AREA RATE SCHEDULE - NONSUPERV...
XF    FLOATING PLANT SCHEDULE (OTHER THAN HOPPER DRE...
XH    FLOATING PLANT (OTHER THAN HOPPER DREDGE) SCHE...
ZA                                       ADMINISTRATIVE
ZP              SCIENTIFIC AND ENGINEERING PROFESSIONAL
ZT                SCIENTIFIC AND ENGINEERING TECHNICIAN
ZZ                                        NONAPPLICABLE

## Accessions
Records of federal employees who joined government. One row = one hiring event.

In [45]:
code_cols = [c for c in a_df.columns if c.endswith("_code")]
print(f"Shape: {a_df.shape[0]:,} rows x {a_df.shape[1]} columns")
print(f"\nCode columns ({len(code_cols)}):")
print(code_cols)
print(f"\nAll columns:")
print(a_df.dtypes.to_string())

Shape: 10,998 rows x 67 columns

Code columns (25):
['accession_category_code', 'agency_code', 'agency_subelement_code', 'appointment_type_code', 'bargaining_unit_code', 'consolidated_statistical_area_code', 'core_based_statistical_area_code', 'duty_station_code', 'duty_station_country_code', 'duty_station_county_code', 'duty_station_state_country_territory_code', 'education_level_code', 'flsa_category_code', 'locality_pay_area_code', 'occupational_category_code', 'occupational_group_code', 'occupational_series_code', 'pay_basis_code', 'pay_plan_code', 'personnel_office_identifier_code', 'position_occupied_code', 'step_or_rate_type_code', 'supervisory_status_code', 'tenure_code', 'work_schedule_code']

All columns:
accession_category                            object
accession_category_code                       object
age_bracket                                   object
agency                                        object
agency_code                                   object
agency_subelement                             object
agency_subelement_code                        object
annualized_adjusted_basic_pay                 object
appointment_not_to_exceed_date                object
appointment_type                              object
appointment_type_code                         object
bargaining_unit                               object
bargaining_unit_code                          object
bargaining_unit_status                        object
cfo_act_agency_indicator                      object
consolidated_statistical_area                 object
consolidated_statistical_area_code            object
core_based_statistical_area                   object
core_based_statistical_area_code              object
count                                          int64
duty_station_code                             object
duty_station_country                          object
duty_station_country_code                     object
duty_station_county                           object
duty_station_county_code                      object
duty_station_state                            object
duty_station_state_abbreviation               object
duty_station_state_country_territory_code     object
education_level                               object
education_level_bracket                       object
education_level_code                          object
flsa_category                                 object
flsa_category_code                            object
grade                                         object
length_of_service_years                      float64
locality_pay_area                             object
locality_pay_area_code                        object
nsftp_indicator                               object
occupational_category                         object
occupational_category_code                    object
occupational_group                            object
occupational_group_code                       object
occupational_series                           object
occupational_series_code                      object
pay_basis                                     object
pay_basis_code                                object
pay_plan                                      object
pay_plan_code                                 object
personnel_action_effective_date_yyyymm         int64
personnel_office_identifier_code              object
position_occupied                             object
position_occupied_code                        object
service_computation_date_leave                object
stem_occupation                               object
stem_occupation_type                          object
step_or_rate_type                             object
step_or_rate_type_code                        object
supervisory_status                            object
supervisory_status_code                      float64
tenure                                        object
tenure_code                                   object
veteran_indicator                             object
work_schedule                                 object
work_schedule_code                            object
year                                           int64
month                                          int64
data_type                                     object

In [46]:
# Sample — working with code columns
a_df[[c for c in a_df.columns if c.endswith("_code")][:6]].head(5)

,accession_category_code,agency_code,agency_subelement_code,appointment_type_code,bargaining_unit_code,consolidated_statistical_area_code
0,AC,AG,AG03,15,7777,NaN
1,AA,AR,ARCE,15,REDACTED,REDACTED
2,AC,AR,ARCE,20,REDACTED,REDACTED
3,AA,AR,ARCH,15,REDACTED,REDACTED
4,AC,AF,AF0M,10,REDACTED,REDACTED

In [47]:
# Key lookup tables for accessions
for key in ["accession_category_code", "agency_code", "tenure_code", "work_schedule_code", "education_level_code", "pay_plan_code", "appointment_type_code"]:
    if key in a_lookups:
        print(f"=== {key} ===")
        print(pd.Series(a_lookups[key]).sort_index().to_string())
        print()
    else:
        print(f"=== {key} === NOT FOUND in lookups")

=== accession_category_code ===
AA                 TRANSFER IN - INDIVIDUAL TRANSFER
AB                       TRANSFER IN - MASS TRANSFER
AC        NEW HIRE - COMPETITIVE SERVICE APPOINTMENT
AD           NEW HIRE - EXCEPTED SERVICE APPOINTMENT
AE    NEW HIRE - SENIOR EXECUTIVE SERVICE (SES) APPT

=== agency_code ===
AB        AMERICAN BATTLE MONUMENTS COMMISSION
AF                 DEPARTMENT OF THE AIR FORCE
AG                   DEPARTMENT OF AGRICULTURE
AH       NAT FOUNDATION ON ARTS AND HUMANITIES
AM           U.S. AGENCY FOR INTERNATIONAL DEV
AR                      DEPARTMENT OF THE ARMY
BF     DEFENSE NUCLEAR FACILITIES SAFETY BOARD
BG        PENSION BENEFIT GUARANTY CORPORATION
BO             OFFICE OF MANAGEMENT AND BUDGET
CM                      DEPARTMENT OF COMMERCE
CT        COMMODITY FUTURES TRADING COMMISSION
DD                       DEPARTMENT OF DEFENSE
DJ                       DEPARTMENT OF JUSTICE
DL                         DEPARTMENT OF LABOR
DN                        DEPARTMENT OF ENERGY
DO                    OFC OF THE NAT CYBER DIR
EB     EXPORT-IMPORT BANK OF THE UNITED STATES
EC                    OFFICE OF ADMINISTRATION
ED                     DEPARTMENT OF EDUCATION
EE     EQUAL EMPLOYMENT OPPORTUNITY COMMISSION
EP             ENVIRONMENTAL PROTECTION AGENCY
FC           FEDERAL COMMUNICATIONS COMMISSION
FD       FEDERAL DEPOSIT INSURANCE CORPORATION
FM      FED MEDIATION AND CONCILIATION SERVICE
FR                      FEDERAL RESERVE SYSTEM
FT                    FEDERAL TRADE COMMISSION
GB                                         DFC
GE    BARRY GOLDWATER SCHOL & EXCEL IN ED FOUN
GJ                              PRESIDIO TRUST
GS             GENERAL SERVICES ADMINISTRATION
HE     DEPARTMENT OF HEALTH AND HUMAN SERVICES
HP        ADV COUNCIL ON HISTORIC PRESERVATION
HS             DEPARTMENT OF HOMELAND SECURITY
HT      HARRY S. TRUMAN SCHOLARSHIP FOUNDATION
HU    DEPARTMENT OF HOUSING AND URBAN DEVELOPM
IB                 U.S.AGENCY FOR GLOBAL MEDIA
IN                      DEPARTMENT OF INTERIOR
LF                 FEDERAL ELECTION COMMISSION
LP                GOVERNMENT PUBLISHING OFFICE
MC                 FEDERAL MARITIME COMMISSION
NF                 NATIONAL SCIENCE FOUNDATION
NL              NATIONAL LABOR RELATIONS BOARD
NN    NAT AERONAUTICS AND SPACE ADMINISTRATION
NP        NATIONAL CAPITAL PLANNING COMMISSION
NQ     NAT ARCHIVES AND RECORDS ADMINISTRATION
NS                   NATIONAL SECURITY COUNCIL
NU               NUCLEAR REGULATORY COMMISSION
NV                      DEPARTMENT OF THE NAVY
OM              OFFICE OF PERSONNEL MANAGEMENT
PU                                 PEACE CORPS
QQ      OFFICE OF NATIONAL DRUG CONTROL POLICY
RF      FED RETIREMENT THRIFT INVESTMENT BOARD
SB               SMALL BUSINESS ADMINISTRATION
SE          SECURITIES AND EXCHANGE COMMISSION
SM                     SMITHSONIAN INSTITUTION
ST                         DEPARTMENT OF STATE
SZ              SOCIAL SECURITY ADMINISTRATION
TB        NATIONAL TRANSPORTATION SAFETY BOARD
TC         U.S. INTERNATIONAL TRADE COMMISSION
TD                DEPARTMENT OF TRANSPORTATION
TN     OFFICE OF THE U.S. TRADE REPRESENTATIVE
TR                      DEPARTMENT OF TREASURY
TS     OFFICE OF SCIENCE AND TECHNOLOGY POLICY
VA              DEPARTMENT OF VETERANS AFFAIRS
ZS     U.S.-CHINA ECONOMIC & SECURITY REV CMSN

=== tenure_code ===
*                                              INVALID
0    NO TENURE GROUP - EMPLOYEES (E.G., TEMPORARIES...
1    TENURE GROUP 1 - CAREER OR SERVING AN APPOINTM...
2    TENURE GROUP 2 - CAREER-CONDITIONAL OR OTHER A...
3    TENURE GROUP 3 - TAPER/TERM OR PROVISIONAL OR ...

=== work_schedule_code ===
F                FULL-TIME
G       FULL-TIME SEASONAL
I             INTERMITTENT
J    INTERMITTENT SEASONAL
P                PART-TIME
Q       PART-TIME SEASONAL

=== education_level_code ===
*                                               INVALID
01    NO FORMAL EDUCATION OR SOME ELEMENTARY SCHOOL ...
02         ELEMENTARY SCHOOL COMPLETED - NO HIGH SCHOOL
03                  SOME HIGH SCHOOL - DID NOT COMPLETE
04    HIGH SCHOOL GRADUATE OR CERTIFICATE OF EQUIVAL...
05     TERMINAL OCCUPATIONAL PROGRAM - DID NOT COMPLETE
06    TERMINAL OCCUPATIONAL PROGRAM - CERTIFICATE OF...
07                    SOME COLLEGE - LESS THAN ONE YEAR
08                                     ONE YEAR COLLEGE
09                                    TWO YEARS COLLEGE
10                                     ASSOCIATE DEGREE
11                                  THREE YEARS COLLEGE
12                                   FOUR YEARS COLLEGE
13                                    BACHELOR'S DEGREE
14                                      POST-BACHELOR'S
15                                   FIRST PROFESSIONAL
16                              POST-FIRST PROFESSIONAL
17                                      MASTER'S DEGREE
18                                        POST-MASTER'S
19                                    SIXTH-YEAR DEGREE
20                                      POST-SIXTH YEAR
21                                     DOCTORATE DEGREE
22                                       POST-DOCTORATE

=== pay_plan_code ===
AD    ADMINISTRATIVELY DETERMINED RATES, NOT ELSEWHE...
AT    FEDERAL AVIATION ADMINISTRATION AIR TRAFFIC CO...
BB            NONSUPERVISORY - NEGOTIATED PAY EMPLOYEES
BN    EMPLOYEES IN THE NAVAL NUCLEAR PROPULSION PROG...
CE                        CONTRACT EDUCATION--YEAR LONG
CG                                     CORPORATE GRADED
CN    BUREAU OF CONSUMER FINANCIAL PROTECT(CFPB) IND...
CT    NONSUPERVISORY EMPLOYEES AT COMMODITY FUTURES ...
CY                      CONTRACT EDUCATION--SCHOOL YEAR
DA                         DEMONSTRATION ADMINISTRATIVE
DB               DEMONSTRATION ENGINEERS AND SCIENTISTS
DE    DEMONSTRATION ENGINEERS AND SCIENTISTS TECHNIC...
DK                        DEMONSTRATION GENERAL SUPPORT
DO    BUSINESS MANAGEMENT AND PROFESSIONAL CAREER PA...
DP                           DEMONSTRATION PROFESSIONAL
DR      DEMONSTRATIION AIR FORCE SCIENTIST AND ENGINEER
ED                               EXPERT (5 U.S.C. 3109)
EE                                       EXPERT (OTHER)
EF                           CONSULTANT (5 U.S.C. 3109)
EI                    ADVISORY COMMITTEE MEMBER (OTHER)
EJ    THE DEPARTMENT OF ENERGY ORGANIZATION ACT EXCE...
EN    NATIONAL NUCLEAR SECURITY ADMINISTRATION EXCEP...
ER    SCIENTIFIC, ENGINEERING & PROFESSONAL PERS OF ...
ES                             SENIOR EXECUTIVE SERVICE
EX                                        EXECUTIVE PAY
FE                               SENIOR FOREIGN SERVICE
FG                      SIMILAR TO THE GENERAL SCHEDULE
FP                            FOREIGN SERVICE PERSONNEL
FV    FEDERAL AVIATION ADMINISTRATION CORE COMPENSAT...
GG                   GRADES SIMILAR TO GENERAL SCHEDULE
GL    GS EMPLOYEES IN GRADES 3 THROUGH 10 PAID A LAW...
GP    GS PHYSICIANS, PODIATRISTS, AND DENTISTS PAID ...
GS                                     GENERAL SCHEDULE
GW    GS EMPLOYEES IN GRADES 1-15 PAID A WILDLAND FI...
IG    INSPECTORS GENERAL WHOSE RATE OF BASIC PAY IS ...
IJ                           IMMIGRATION JUDGE SCHEDULE
KJ    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
KX    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
LE        UNITED STATES SECRET SERVICE UNIFORM DIVISION
NB       OFFICE OF THE COMPTROLLER OF THE CURRENCY ONLY
ND             DEMONSTRATION SCIENTIFIC AND ENGINEERING
NH    BUSINESS MANAGEMENT AND TECHNICAL MANAGEMENT P...
NJ                         TECHNICAL MANAGEMENT SUPPORT
NK                               ADMINISTRATION SUPPORT
NL    NONAPPROPRIATED FUNDS - LEADER - FEDERAL WAGE ...
NN    EMPLOYEES IN THE NATIONAL NUCLEAR SECURITY ADM...
NO               ADMINISTRATIVE SPECIALIST/PROFESSIONAL
NP                 SCIENCE AND ENGINEERING PROFESSIONAL
NQ    EMPLOYEES IN THE NATIONAL NUCLEAR SECUIRTY ADM...
NT           DEMONSTRATION ADMINISTRATIVE AND TECHNICAL
NV    EMPLOYEES IN THE NATIONAL NUCLEAR SECURITY ADM...
RA    DEPARTMENT OF AGRICULTURE POSITIONS IN THE SEN...
RG    SCIENTISTS APPOINTED AS FELLOWS AND COMPENSATE...
SK    NON-SUPERVISORY POSITIONS EMPLOYED BY THE SECU...
SL                               SENIOR LEVEL POSITIONS
SO    EXECUTIVE POSITIONS EMPLOYED BY THE SECURITIES...
SP                                          PARK POLICE
SR              STATUTORY RATES NOT ELSEWHERE SPECIFIED
ST                          SCIENTIFIC AND PROFESSIONAL
SV    TRANSPORTATION SECURITY ADMINISTRATION EMPLOYE...
SW    TRANSPORTATION SECURITY ADMINISTRATION EXECUTIVES
TP                                   TEACHING POSITIONS
TR    POLICE FORCES OF THE U.S. MINT AND BUREAU OF E...
VC                                      CANTEEN SERVICE
VM                                   MEDICAL AND DENTAL
VN                                              NURSING
WB    WAGE POSITIONS UNDER THE FEDERAL WAGE SYSTEM N...
WD    PRODUCTION FACILITATING NON-SUPERVISORY - FEDE...
WG    NONSUPERVISORY PAY SCHEDULES - FEDERAL WAGE SY...
WJ          HOPPER DREDGE SCHEDULE--FEDERAL WAGE SYSTEM
WL            LEADER PAY SCHEDULE - FEDERAL WAGE SYSTEM
WM                MARITIME PAY SCHEDULES--5 U.S.C. 5348
WS      SUPERVISORY PAY SCHEDULES - FEDERAL WAGE SYSTEM
WT    APPRENTICES AND SHOP TRAINEES - FEDERAL WAGE S...
WU    AIRCRAFT, ELECTRONIC EQUIPMENT, AND OPTICAL IN...
WY    NAVIGATIONAL LOCK & DAM OPERATION & MAINTENANC...
XF    FLOATING PLANT SCHEDULE (OTHER THAN HOPPER DRE...
XH    FLOATING PLANT (OTHER THAN HOPPER DREDGE) SCHE...
ZA                                       ADMINISTRATIVE
ZP              SCIENTIFIC AND ENGINEERING PROFESSIONAL
ZS                               ADMINISTRATIVE SUPPORT
ZZ                                        NONAPPLICABLE

=== appointment_type_code ===
*                                               INVALID
10               CAREER (COMPETITIVE SERVICE PERMANENT)
15    CAREER-CONDITIONAL (COMPETITIVE SERVICE PERMAN...
20     NONPERMANENT (COMPETITTIVE SERVICE NONPERMANENT)
30              SCHEDULE A (EXCEPTED SERVICE PERMANENT)
32              SCHEDULE B (EXCEPTED SERVICE PERMANENT)
35              SCHEDULE D (EXCEPTED SERVICE PERMANENT)
38                   OTHER (EXCEPTED SERVICE PERMANENT)
40           SCHEDULE A (EXCEPTED SERVICE NONPERMANENT)
42           SCHEDULE B (EXCEPTED SERVICE NONPERMANENT)
44           SCHEDULE C (EXCEPTED SERVICE NONPERMANENT)
45           SCHEDULE D (EXCEPTED SERVICE NONPERMANENT)
46            EXECUTIVE (EXCEPTED SERVICE NONPERMANENT)
48                OTHER (EXCEPTED SERVICE NONPERMANENT)
50          CAREER (SENIOR EXECUTIVE SERVICE PERMANENT)
55       NONCAREER (SENIOR EXECUTIVE SERVICE PERMANENT)
60    LIMITED TERM (SENIOR EXECUTIVE SERVICE NONPERM...

## Employment
A snapshot of the full federal workforce at a point in time. One row = one active employee record.

In [42]:
code_cols = [c for c in e_df.columns if c.endswith("_code")]
print(f"Shape: {e_df.shape[0]:,} rows x {e_df.shape[1]} columns")
print(f"\nCode columns ({len(code_cols)}):")
print(code_cols)
print(f"\nAll columns:")
print(e_df.dtypes.to_string())

Shape: 2,028,138 rows x 64 columns

Code columns (24):
['agency_code', 'agency_subelement_code', 'appointment_type_code', 'bargaining_unit_code', 'consolidated_statistical_area_code', 'core_based_statistical_area_code', 'duty_station_code', 'duty_station_country_code', 'duty_station_county_code', 'duty_station_state_country_territory_code', 'education_level_code', 'flsa_category_code', 'locality_pay_area_code', 'occupational_category_code', 'occupational_group_code', 'occupational_series_code', 'pay_basis_code', 'pay_plan_code', 'personnel_office_identifier_code', 'position_occupied_code', 'step_or_rate_type_code', 'supervisory_status_code', 'tenure_code', 'work_schedule_code']

All columns:
age_bracket                                   object
agency                                        object
agency_code                                   object
agency_subelement                             object
agency_subelement_code                        object
annualized_adjusted_basic_pay                 object
appointment_type                              object
appointment_type_code                         object
bargaining_unit                               object
bargaining_unit_code                          object
bargaining_unit_status                        object
cfo_act_agency_indicator                      object
consolidated_statistical_area                 object
consolidated_statistical_area_code            object
core_based_statistical_area                   object
core_based_statistical_area_code              object
count                                          int64
duty_station_code                             object
duty_station_country                          object
duty_station_country_code                     object
duty_station_county                           object
duty_station_county_code                      object
duty_station_state                            object
duty_station_state_abbreviation               object
duty_station_state_country_territory_code     object
education_level                               object
education_level_bracket                       object
education_level_code                          object
flsa_category                                 object
flsa_category_code                            object
grade                                         object
length_of_service_years                      float64
locality_pay_area                             object
locality_pay_area_code                        object
nsftp_indicator                               object
occupational_category                         object
occupational_category_code                    object
occupational_group                            object
occupational_group_code                       object
occupational_series                           object
occupational_series_code                      object
pay_basis                                     object
pay_basis_code                                object
pay_plan                                      object
pay_plan_code                                 object
personnel_office_identifier_code              object
position_occupied                             object
position_occupied_code                        object
service_computation_date_leave                object
snapshot_yyyymm                                int64
stem_occupation                               object
stem_occupation_type                          object
step_or_rate_type                             object
step_or_rate_type_code                        object
supervisory_status                            object
supervisory_status_code                       object
tenure                                        object
tenure_code                                   object
veteran_indicator                             object
work_schedule                                 object
work_schedule_code                            object
year                                           int64
month                                          int64
data_type                                     object

In [43]:
# Sample — working with code columns
e_df[[c for c in e_df.columns if c.endswith("_code")][:6]].head(5)

,agency_code,agency_subelement_code,appointment_type_code,bargaining_unit_code,consolidated_statistical_area_code,core_based_statistical_area_code
0,DJ,DJ03,10,REDACTED,REDACTED,REDACTED
1,FW,FW00,30,8888,548,47900
2,DJ,DJ09,15,REDACTED,REDACTED,REDACTED
3,HS,HSBC,38,REDACTED,REDACTED,REDACTED
4,DJ,DJ09,10,REDACTED,REDACTED,REDACTED

In [44]:
# Key lookup tables for employment
for key in ["agency_code", "pay_plan_code", "tenure_code", "work_schedule_code", "education_level_code", "occupational_category_code", "supervisory_status_code"]:
    if key in e_lookups:
        print(f"=== {key} ===")
        print(pd.Series(e_lookups[key]).sort_index().to_string())
        print()

=== agency_code ===
AA       ADMIN CONFERENCE OF THE UNITED STATES
AB        AMERICAN BATTLE MONUMENTS COMMISSION
AF                 DEPARTMENT OF THE AIR FORCE
AG                   DEPARTMENT OF AGRICULTURE
AH       NAT FOUNDATION ON ARTS AND HUMANITIES
AM           U.S. AGENCY FOR INTERNATIONAL DEV
AN              AFRICAN DEVELOPMENT FOUNDATION
AP             APPALACHIAN REGIONAL COMMISSION
AR                      DEPARTMENT OF THE ARMY
AU           FEDERAL LABOR RELATIONS AUTHORITY
AW                  ARCTIC RESEARCH COMMISSION
BD              MERIT SYSTEMS PROTECTION BOARD
BF     DEFENSE NUCLEAR FACILITIES SAFETY BOARD
BG        PENSION BENEFIT GUARANTY CORPORATION
BH    CMSN FOR PRES OF AMERICA'S HERITAGE ABRD
BK     JAMES MADISON MEMORIAL FELLOWSHIP FOUND
BO             OFFICE OF MANAGEMENT AND BUDGET
BT    ARCHITECTL & TRANS BARRIER COMPLIANCE BD
BW        NUCLEAR WASTE TECHNICAL REVIEW BOARD
CC                  COMMISSION ON CIVIL RIGHTS
CE                COUNCIL OF ECONOMIC ADVISERS
CF                     COMMISSION OF FINE ARTS
CM                      DEPARTMENT OF COMMERCE
CT        COMMODITY FUTURES TRADING COMMISSION
CU        NATIONAL CREDIT UNION ADMINISTRATION
CX      NAT CMSN ON LIBRARIES AND INFO SCIENCE
DA                    DELTA REGIONAL AUTHORITY
DB      PUBLIC INTEREST DECLASSIFICATION BOARD
DD                       DEPARTMENT OF DEFENSE
DG         NORTHERN BORDER REGIONAL COMMISSION
DJ                       DEPARTMENT OF JUSTICE
DL                         DEPARTMENT OF LABOR
DN                        DEPARTMENT OF ENERGY
DO                    OFC OF THE NAT CYBER DIR
DQ                           DENALI COMMISSION
EB     EXPORT-IMPORT BANK OF THE UNITED STATES
EC                    OFFICE OF ADMINISTRATION
ED                     DEPARTMENT OF EDUCATION
EE     EQUAL EMPLOYMENT OPPORTUNITY COMMISSION
EO    MORRIS K. UDALL & STEWART L. UDALL FOUND
EP             ENVIRONMENTAL PROTECTION AGENCY
EQ     COUNCIL ON ENVIR QUAL/OFC OF ENVIR QUAL
EW                TRADE AND DEVELOPMENT AGENCY
FC           FEDERAL COMMUNICATIONS COMMISSION
FD       FEDERAL DEPOSIT INSURANCE CORPORATION
FI       FEDERAL FINANCIAL INST. EXAM. COUNCIL
FJ     CHEMICAL SAFETY/HAZARD INVESTIGATION BD
FK    FARM CREDIT SYSTEM INSURANCE CORPORATION
FL                  FARM CREDIT ADMINISTRATION
FM      FED MEDIATION AND CONCILIATION SERVICE
FQ     COURT SERVICES AND OFFENDR SUPERVSN AGY
FR                      FEDERAL RESERVE SYSTEM
FT                    FEDERAL TRADE COMMISSION
FW                   OFFICE OF SPECIAL COUNSEL
GB                                         DFC
GC    GULF COAST ECOSYSTEM RESTORATION COUNCIL
GE    BARRY GOLDWATER SCHOL & EXCEL IN ED FOUN
GG                 OFFICE OF GOVERNMENT ETHICS
GJ                              PRESIDIO TRUST
GQ              ELECTION ASSISTANCE COMMISSION
GS             GENERAL SERVICES ADMINISTRATION
GU        THE US SEMIQUINCENTENNIAL COMMISSION
GW     INTER BOUND AND WATER COMM U.S. SECTION
GX     INTERNAT BOUNDARY CMSN: U.S. AND CANADA
GY     INTERNATIONAL JOINT CMSN: U.S. & CANADA
HB    CMTE FOR PURCH FRM PPLE BLIND OR SEV DIS
HD              U.S. HOLOCAUST MEMORIAL MUSEUM
HE     DEPARTMENT OF HEALTH AND HUMAN SERVICES
HF              FEDERAL HOUSING FINANCE AGENCY
HP        ADV COUNCIL ON HISTORIC PRESERVATION
HS             DEPARTMENT OF HOMELAND SECURITY
HT      HARRY S. TRUMAN SCHOLARSHIP FOUNDATION
HU    DEPARTMENT OF HOUSING AND URBAN DEVELOPM
HW    U.S. INTERAGENCY COUNCIL ON HOMELESSNESS
IB                 U.S.AGENCY FOR GLOBAL MEDIA
IF                   INTER-AMERICAN FOUNDATION
IG     COUNCIL OF INSP. GEN. ON INTEG.& EFFIC.
IN                      DEPARTMENT OF INTERIOR
JL                             JUDICIAL BRANCH
KS     CORP FOR NATIONAL AND COMMUNITY SERVICE
KY               PUBLIC BUILDINGS REFORM BOARD
LF                 FEDERAL ELECTION COMMISSION
LP                GOVERNMENT PUBLISHING OFFICE
MA                    MARINE MAMMAL COMMISSION
MC                 FEDERAL MARITIME COMMISSION
MI            MILLENNIUM CHALLENGE CORPORATION
NF                 NATIONAL SCIENCE FOUNDATION
NK              NATIONAL COUNCIL ON DISABILITY
NL              NATIONAL LABOR RELATIONS BOARD
NM                    NATIONAL MEDIATION BOARD
NN    NAT AERONAUTICS AND SPACE ADMINISTRATION
NP        NATIONAL CAPITAL PLANNING COMMISSION
NQ     NAT ARCHIVES AND RECORDS ADMINISTRATION
NS                   NATIONAL SECURITY COUNCIL
NU               NUCLEAR REGULATORY COMMISSION
NV                      DEPARTMENT OF THE NAVY
OM              OFFICE OF PERSONNEL MANAGEMENT
OS    OCCUPATIONAL SAFETY & HEALTH REVIEW CMSN
PU                                 PEACE CORPS
QQ      OFFICE OF NATIONAL DRUG CONTROL POLICY
RF      FED RETIREMENT THRIFT INVESTMENT BOARD
RH                ARMED FORCES RETIREMENT HOME
RJ         CIVIL RIGHTS COLD CASE REVIEW BOARD
RO       MEDICAID & CHIP PAYMENT & ACCESS COMM
RR                   RAILROAD RETIREMENT BOARD
RS      FED MINE SAFETY AND HEALTH REVIEW CMSN
SB               SMALL BUSINESS ADMINISTRATION
SE          SECURITIES AND EXCHANGE COMMISSION
SK          CONSUMER PRODUCT SAFETY COMMISSION
SM                     SMITHSONIAN INSTITUTION
SS                    SELECTIVE SERVICE SYSTEM
ST                         DEPARTMENT OF STATE
SZ              SOCIAL SECURITY ADMINISTRATION
TB        NATIONAL TRANSPORTATION SAFETY BOARD
TC         U.S. INTERNATIONAL TRADE COMMISSION
TD                DEPARTMENT OF TRANSPORTATION
TN     OFFICE OF THE U.S. TRADE REPRESENTATIVE
TR                      DEPARTMENT OF TREASURY
TS     OFFICE OF SCIENCE AND TECHNOLOGY POLICY
TW                SURFACE TRANSPORTATION BOARD
UJ         JAPAN-UNITED STATES FRIENDSHIP CMSN
UT    UTAH RECLAMATN MITIGATN & CONSERVTN CMSN
VA              DEPARTMENT OF VETERANS AFFAIRS
VD       PRIVACY AND CIVIL LIBERTIES OVERSIGHT
WK        FEDERAL PERMITTING IMPROVEMENT STEER
WU        SOUTHWEST BORDER REGIONAL COMMISSION
ZP    U.S. CMSN ON INTERNATL RELIGIOUS FREEDOM
ZS     U.S.-CHINA ECONOMIC & SECURITY REV CMSN

=== pay_plan_code ===
*                                               INVALID
AA                        ADMINISTRATIVE APPEALS JUDGES
AD    ADMINISTRATIVELY DETERMINED RATES, NOT ELSEWHE...
AJ                                ADMINISTRATIVE JUDGES
AL                            ADMINISTRATIVE LAW JUDGES
AT    FEDERAL AVIATION ADMINISTRATION AIR TRAFFIC CO...
BB            NONSUPERVISORY - NEGOTIATED PAY EMPLOYEES
BL                    LEADER - NEGOTIATED PAY EMPLOYEES
BN    EMPLOYEES IN THE NAVAL NUCLEAR PROPULSION PROG...
BR    EMPLOYEES IN NAVAL NUCLEAR PROPULSION PROGRAM ...
BS               SUPERVISORY - NEGOTIATED PAY EMPLOYEES
BV    EMPLOYEES IN THE NAVAL NUCLEAR PROPULSION PROG...
CA                            BOARD OF CONTRACT APPEALS
CE                        CONTRACT EDUCATION--YEAR LONG
CG                                     CORPORATE GRADED
CM    FDIC SUPERVISORY AND MANAGERIAL POSITIONS BELO...
CN    BUREAU OF CONSUMER FINANCIAL PROTECT(CFPB) IND...
CT    NONSUPERVISORY EMPLOYEES AT COMMODITY FUTURES ...
CU                               CREDIT UNION EMPLOYEES
CX    SENIOR EXPERT POSITIONS IN THE FEDERAL DEPOSIT...
CY                      CONTRACT EDUCATION--SCHOOL YEAR
DA                         DEMONSTRATION ADMINISTRATIVE
DB               DEMONSTRATION ENGINEERS AND SCIENTISTS
DC    POSITIONS DESIGNATED AND PAID RATES OF BASIC P...
DE    DEMONSTRATION ENGINEERS AND SCIENTISTS TECHNIC...
DG                                DEMONSTRATION GENERAL
DJ                         DEMONSTRATION ADMINISTRATIVE
DK                        DEMONSTRATION GENERAL SUPPORT
DL    POSITIONS DESIGNATED AND PAID RATES OF BASIC P...
DN    DEFENSE NUCLEAR FACILITIES SAFETY BOARD EXCEPT...
DO    BUSINESS MANAGEMENT AND PROFESSIONAL CAREER PA...
DP                           DEMONSTRATION PROFESSIONAL
DR      DEMONSTRATIION AIR FORCE SCIENTIST AND ENGINEER
DS                             DEMONSTRATION SPECIALIST
DT                             DEMONSTRATION TECHNICIAN
DU    MISSION SUPPORT CAREER PATH, AIR FORCE RESEARC...
DX    TECHNICIAN CAREER PATH, AIR FORCE RESEARCH LAB...
ED                               EXPERT (5 U.S.C. 3109)
EE                                       EXPERT (OTHER)
EF                           CONSULTANT (5 U.S.C. 3109)
EG                                   CONSULTANT (OTHER)
EH            ADVISORY COMMITTEE MEMBER (5 U.S.C. 3109)
EI                    ADVISORY COMMITTEE MEMBER (OTHER)
EJ    THE DEPARTMENT OF ENERGY ORGANIZATION ACT EXCE...
EK    THE NATIONAL DEFENSE AUTHORIZATION ACT OF 1995...
EL    NON-EXECUTIVE POSITIONS AT THE FEDERAL HOUSING...
EM                  FDIC EXECUTIVE-LEVEL POSITIONS ONLY
EN    NATIONAL NUCLEAR SECURITY ADMINISTRATION EXCEP...
ER    SCIENTIFIC, ENGINEERING & PROFESSONAL PERS OF ...
ES                             SENIOR EXECUTIVE SERVICE
ET    PROGRAM DIRECTOR OF THE ADVANCED RESEARCH PROJ...
EV    FEDERAL AVIATION ADMINISTRATION EXECUTIVE COMP...
EX                                        EXECUTIVE PAY
FE                               SENIOR FOREIGN SERVICE
FG                      SIMILAR TO THE GENERAL SCHEDULE
FJ                  OFFICIALS ON NONCAREER APPOINTMENTS
FL    WAGE LEADERS (SIMILAR TO THE LEADER PAY SCHEDU...
FO                             FOREIGN SERVICE OFFICERS
FP                            FOREIGN SERVICE PERSONNEL
FS    WAGE SUPERVISORS (SIMILAR TO THE SUPERVISORY P...
FV    FEDERAL AVIATION ADMINISTRATION CORE COMPENSAT...
FW    WAGE GRADE (SIMILAR TO THE NONSUPERVISORY PAY ...
GE    U.S. GOVERNMENT PRINTING OFFICE EMPLOYEES FORM...
GG                   GRADES SIMILAR TO GENERAL SCHEDULE
GI    U.S. GOVERNMENT PRINTING OFFICE CRIMINAL INVES...
GL    GENERAL SCHEDULE EMPLOYEES IN GRADES 3 THROUGH...
GM    EMPLOYEES COVERED BY THE PERFORMANCE MANAGEMEN...
GP    GS PHYSICIANS, PODIATRISTS, AND DENTISTS PAID ...
GR    GM PHYSICIANS, PODIATRISTS, AND DENTISTS PAID ...
GS                                     GENERAL SCHEDULE
GW    GS EMPLOYEES IN GRADES 1-15 PAID A WILDLAND FI...
IC    EMPLOYEES HOLDING INCIDENT MANAGEMENT CADRE OF...
IE    SENIOR INTELLIGENCE EXECUTIVE SERVICE (SIES) P...
IG    INSPECTORS GENERAL WHOSE RATE OF BASIC PAY IS ...
IH    TEMPORARY EMPLOYEES HIRED IN RESPONSE TO A DIS...
IJ                           IMMIGRATION JUDGE SCHEDULE
IM    EMPLOYEES HOLDING INCIDENT MANAGEMENT POSITION...
IP       SENIOR INTELLIGENCE PROFESSIONAL (SIP) PROGRAM
IR    INTERNAL REVENUE SERVICE BROADBAND CLASSIFICAT...
IT    EMPLOYEES APPOINTED AND COMPENSATED UNDER SECT...
KA                                            KIESS ACT
KB    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
KE    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
KG                            NON-CRAFT NON-SUPERVISORY
KI    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
KJ    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
KL                                   NON-CRAFT - LEADER
KM    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
KO    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
KP    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
KS                              NON-CRAFT - SUPERVISORY
KX    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
KY    GOVERNMENT PRINTING OFFICE NEGOTIATED RATES FO...
LE        UNITED STATES SECRET SERVICE UNIFORM DIVISION
LL     EXECUTIVES AT THE FEDERAL HOUSING FINANCE AGENCY
MC    EMPLOYEES OF THE MILLENNIUM CHALLENGE CORPORAT...
NB       OFFICE OF THE COMPTROLLER OF THE CURRENCY ONLY
NC                               ADMINISTRATIVE SUPPORT
ND             DEMONSTRATION SCIENTIFIC AND ENGINEERING
NF    EMPLOYEES IN THE NATIONAL NUCLEAR SECURITY ADM...
NG                        DEMONSTRATION GENERAL SUPPORT
NH    BUSINESS MANAGEMENT AND TECHNICAL MANAGEMENT P...
NJ                         TECHNICAL MANAGEMENT SUPPORT
NK                               ADMINISTRATION SUPPORT
NL    NONAPPROPRIATED FUNDS - LEADER - FEDERAL WAGE ...
NM                             SUPERVISORS AND MANAGERS
NN    EMPLOYEES IN THE NATIONAL NUCLEAR SECURITY ADM...
NO               ADMINISTRATIVE SPECIALIST/PROFESSIONAL
NP                 SCIENCE AND ENGINEERING PROFESSIONAL
NQ    EMPLOYEES IN THE NATIONAL NUCLEAR SECUIRTY ADM...
NR                    SCIENCE AND ENGINEERING TECHNICAL
NS    NONAPPROPRIATED FUNDS - SUPERVISORY - FEDERAL ...
NT           DEMONSTRATION ADMINISTRATIVE AND TECHNICAL
NU    EMPLOYEES IN THE NATIONAL NUCLEAR SECURITY ADM...
NV    EMPLOYEES IN THE NATIONAL NUCLEAR SECURITY ADM...
NX    EXECUTIVE-LEVEL AND MANAGERIAL POSITIONS IN TH...
NY    ALL OTHER POSITIONS IN THE CORPORATION FOR NAT...
NZ                      NATIONAL ZOOLOGICAL PARK POLICE
OR    EMPLOYEES OF THE OFFICE OF FINANCIAL RESEARCH ...
PG                               PRINTING OFFICE GRADES
PQ         GOVERNMENT PRINTING OFFICE, POLICE, DAY RATE
PU    GOVERNMENT PRINTING OFFICE, WHITE-COLLAR, 10% ...
PZ    GOVERNMENT PRINTING OFFICE, POLICE, 10% NIGHT ...
RA    DEPARTMENT OF AGRICULTURE POSITIONS IN THE SEN...
RF    EMPLOYEES APPOINTED AND COMPENSATED AS SPECIAL...
RG    SCIENTISTS APPOINTED AS FELLOWS AND COMPENSATE...
RS                   SENIOR BIOMEDICAL RESEARCH SERVICE
SK    NON-SUPERVISORY POSITIONS EMPLOYED BY THE SECU...
SL                               SENIOR LEVEL POSITIONS
SN                                  SENIOR LEVEL SYSTEM
SO    EXECUTIVE POSITIONS EMPLOYED BY THE SECURITIES...
SP                                          PARK POLICE
SR              STATUTORY RATES NOT ELSEWHERE SPECIFIED
SS                               SENIOR STAFF POSITIONS
ST                          SCIENTIFIC AND PROFESSIONAL
SV    TRANSPORTATION SECURITY ADMINISTRATION EMPLOYE...
SW    TRANSPORTATION SECURITY ADMINISTRATION EXECUTIVES
TP                                   TEACHING POSITIONS
TR    POLICE FORCES OF THE U.S. MINT AND BUREAU OF E...
VC                                      CANTEEN SERVICE
VE             VETERANS CANTEEN SERVICE EXECUTIVES ONLY
VH         PROFESSIONAL, ADMINISTRATIVE, AND MANAGERIAL
VM                                   MEDICAL AND DENTAL
VN                                              NURSING
VP       CLINICAL PODIATRISTS AND OPTOMETRISTS SCHEDULE
WA    NAVIGATIONAL LOCK AND DAM OPERATIONS AND MAINT...
WB    WAGE POSITIONS UNDER THE FEDERAL WAGE SYSTEM N...
WD    PRODUCTION FACILITATING NON-SUPERVISORY - FEDE...
WE                               CURRENCY MANUFACTURING
WG    NONSUPERVISORY PAY SCHEDULES - FEDERAL WAGE SY...
WJ          HOPPER DREDGE SCHEDULE--FEDERAL WAGE SYSTEM
WK               HOPPER DREDGE SCHEDULE, NONSUPERVISORY
WL            LEADER PAY SCHEDULE - FEDERAL WAGE SYSTEM
WM                MARITIME PAY SCHEDULES--5 U.S.C. 5348
WN    PRODUCTION FACILITATING SUPERVISORY FEDERAL WA...
WO    NAVIGATIONAL LOCK AND DAM OPERATION AND MAINTE...
WQ    AIRCRAFT, ELECTRONIC EQUIPMENT, AND OPTICAL IN...
WS      SUPERVISORY PAY SCHEDULES - FEDERAL WAGE SYSTEM
WT    APPRENTICES AND SHOP TRAINEES - FEDERAL WAGE S...
WU    AIRCRAFT, ELECTRONIC EQUIPMENT, AND OPTICAL IN...
WY    NAVIGATIONAL LOCK & DAM OPERATION & MAINTENANC...
XA    SPECIAL OVERLAP AREA RATE SCHEDULE - NONSUPERV...
XB    SPECIAL OVERLAP AREA RATE SCHEDULE - LEADER - ...
XC    SPECIAL OVERLAP AREA RATE SCHEDULE - SUPERVISO...
XE    SUPERVISORS OF NEGOTIATED RATE EMPLOYEES--FEDE...
XF    FLOATING PLANT SCHEDULE (OTHER THAN HOPPER DRE...
XG    FLOATING PLANT (OTHER THAN HOPPER DREDGE) SCHE...
XH    FLOATING PLANT (OTHER THAN HOPPER DREDGE) SCHE...
XR    NON-SUPERVISORY U.S. ARMY CORPS OF ENGINEERS P...
ZA                                       ADMINISTRATIVE
ZP              SCIENTIFIC AND ENGINEERING PROFESSIONAL
ZS                               ADMINISTRATIVE SUPPORT
ZT                SCIENTIFIC AND ENGINEERING TECHNICIAN
ZZ                                        NONAPPLICABLE

=== tenure_code ===
*                                              INVALID
0    NO TENURE GROUP - EMPLOYEES (E.G., TEMPORARIES...
1    TENURE GROUP 1 - CAREER OR SERVING AN APPOINTM...
2    TENURE GROUP 2 - CAREER-CONDITIONAL OR OTHER A...
3    TENURE GROUP 3 - TAPER/TERM OR PROVISIONAL OR ...

=== work_schedule_code ===
*                                              INVALID
B                                          BAYLOR PLAN
F                                            FULL-TIME
G                                   FULL-TIME SEASONAL
I                                         INTERMITTENT
J                                INTERMITTENT SEASONAL
P                                            PART-TIME
Q                                   PART-TIME SEASONAL
R    A SCHEDULE REQUIRED WHEN AN EMPLOYEE HAS ELECT...
S                                 PART-TIME JOB SHARER
T                        PART-TIME SEASONAL JOB SHARER

=== education_level_code ===
*                                               INVALID
01    NO FORMAL EDUCATION OR SOME ELEMENTARY SCHOOL ...
02         ELEMENTARY SCHOOL COMPLETED - NO HIGH SCHOOL
03                  SOME HIGH SCHOOL - DID NOT COMPLETE
04    HIGH SCHOOL GRADUATE OR CERTIFICATE OF EQUIVAL...
05     TERMINAL OCCUPATIONAL PROGRAM - DID NOT COMPLETE
06    TERMINAL OCCUPATIONAL PROGRAM - CERTIFICATE OF...
07                    SOME COLLEGE - LESS THAN ONE YEAR
08                                     ONE YEAR COLLEGE
09                                    TWO YEARS COLLEGE
10                                     ASSOCIATE DEGREE
11                                  THREE YEARS COLLEGE
12                                   FOUR YEARS COLLEGE
13                                    BACHELOR'S DEGREE
14                                      POST-BACHELOR'S
15                                   FIRST PROFESSIONAL
16                              POST-FIRST PROFESSIONAL
17                                      MASTER'S DEGREE
18                                        POST-MASTER'S
19                                    SIXTH-YEAR DEGREE
20                                      POST-SIXTH YEAR
21                                     DOCTORATE DEGREE
22                                       POST-DOCTORATE

=== occupational_category_code ===
*               INVALID
A        ADMINISTRATIVE
B           BLUE COLLAR
C              CLERICAL
O    OTHER WHITE COLLAR
P          PROFESSIONAL
T             TECHNICAL

=== supervisory_status_code ===
*                       INVALID
2         SUPERVISOR OR MANAGER
4             SUPERVISOR (CSRA)
5    MANAGEMENT OFFICIAL (CSRA)
6                        LEADER
7                   TEAM LEADER
8           ALL OTHER POSITIONS